version: '3'

services:
  app:
    image: framadate
    container_name: framadate
    volumes:
      - ./logo.png:/var/www/html/images/logo-framadate.png
      - ./config.php:/var/www/html/app/inc/config.php
    depends_on:
      - db
    ports:
      - 8082:80
  db:
    image: mysql
    container_name: framadate-db
    environment:
      - MYSQL_ROOT_PASSWORD=${db_password}
      - MYSQL_DATABASE=framadate